Create a useValue hook
mediamonks/react-hooks pull request #126
Opened 2023-04-04 13:17 UTC by ThaNarie

2023-04-04 13:32 UTC, mmnathan commented
Did you consider a more descriptive name like `useInitialValue/useStaticValue/useIdentity` (ok the last one is too obscure)?

2023-04-04 13:35 UTC, mmnathan commented
Should it also accept a direct (non-lazy) value to be consistent with `useState`? I can imagine this being useful when you'd like the initial value of a prop.

2023-04-04 13:41 UTC, ThaNarie commented
> Did you consider a more descriptive name like useInitialValue/useStaticValue/useIdentity (ok the last one is too obscure)?

I didn't, but I like `useStaticValue` :)

> Should it also accept a direct (non-lazy) value to be consistent with useState? I can imagine this being useful when you'd like the initial value of a prop.

I guess that could be useful for that specific scenario, but you can already `useRef` for that. The main reason for this hook is to work with values that should be computed once (that's where useRef fails), or would create a new reference every time (that's where useMemo is cumbersome, and not 100% safe).

2023-04-05 06:54 UTC, leroykorterink requested changes

2023-04-05 06:54 UTC, leroykorterink commented on src/hooks/useValue/useValue.ts
> +  if (!valueRef.current) {
So if the initial value is falsy the value can still change? I think that shouldn't happen right?

I'd use the useState hook in the implementation.

```ts
const [value] = useState(initalizeFunction):
return value;
```

2023-04-05 10:32 UTC, ThaNarie commented
@mmnathan I updated the implementation (and the name), and now it does support the same **initial value** as `useState` does :) More by accident because internally it uses `useState`.

2023-04-05 10:46 UTC, leroykorterink approved these changes

2023-04-05 11:03 UTC, merged