Create unwrapRefs function
mediamonks/react-hooks pull request #13
Opened 2022-12-13 14:17 UTC by leroykorterink

2022-12-13 14:26 UTC, ThaNarie requested changes

2022-12-13 14:26 UTC, ThaNarie commented on src/unwrapRefs/unwrapRefs.stories.mdx
> +## Usage
Please copy fixed version of example from the other PR.

2022-12-13 14:39 UTC, leroykorterink commented on src/unwrapRefs/unwrapRefs.ts
> +  }
You're losing the key type with `Object.keys` (it'll just be a `string`) so chose to write it out like this. Typescript maintains the type of `key` with `for in` (`Extract<keyof T, string>`), the `Object.hasOwn` is enforced by `eslint` when `for in` is used.

https://eslint.org/docs/latest/rules/guard-for-in

2022-12-13 14:43 UTC, ThaNarie commented on src/unwrapRefs/unwrapRefs.ts
> +  }
Ah yes, the types 😄

2022-12-14 09:07 UTC, ThaNarie requested changes

2022-12-14 09:07 UTC, ThaNarie commented on src/unwrapRefs/unwrapRefs.stories.mdx
> +    console.log(elements); // Array<HTMLButtonElement | null> | null
```suggestion
    const { heading, buttons } = unwrapRefs(refs);

    console.log(heading); // HTMLHeadingElement | null
    console.log(buttons); // Array<HTMLButtonElement | null> | null
```

2022-12-14 16:18 UTC, ThaNarie approved these changes

2022-12-14 16:36 UTC, merged